# Site settings
title: 			Vizabi
email: 			info@gapminder.org
description: 	Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: 		""
url: 			"http://vizabi.org"
github_username:  Gapminder/vizabi

# Build settings
markdown: kramdown

# Permalinks
permalink:           pretty
relative_permalinks: true

#Blog
highlighter:         pygments
excerpt_separator:   <!--more-->
paginate:			 3
paginate_path: 		 "/blog/:num/"

# Assets
vizabi_version:		develop

menu:
  - title: Home
    url: /
  - title: Examples
    url: /examples/
  - title: Docs
    url: /docs/
  - title: Blog
    url: /blog/

assets:
  js_compressor:  	uglifier
  css_compressor: 	sass

exclude: [Gemfile, Gemfile.lock, README.md]

categories: [docs]

collections:
  documentation:
    output: false
  examples:
    output: true